apiVersion: 1

providers:
  - name: 'Dashboards Evasao MLOps'
    orgId: 1
    folder: ''
    type: file
    uid: grafanacloud-prom
    disableDeletion: false
    updateIntervalSeconds: 10
    options:
      path: /etc/grafana/provisioning/dashboards