name: evasao-mlops

services:
  # -------------------------------------
  # 1. BANCO DE DADOS E ARMAZENAMENTO
  # -------------------------------------
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mlops_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001" # MinIO Console
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - mlops_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio-create-bucket:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb myminio/mlflow-artifacts || true;
      /usr/bin/mc anonymous set public myminio/mlflow-artifacts || true;
      exit 0;
      "
    networks:
      - mlops_net

  # -------------------------------------
  # 2. MLFLOW (TRACKING & REGISTRY)
  # -------------------------------------
  mlflow:
    build:
      context: ./config
      dockerfile: Dockerfile.mlflow
    container_name: mlflow_server
    ports:
      - "5050:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
    depends_on:
      postgres:
        condition: service_healthy
      minio-create-bucket:
        condition: service_completed_successfully
    command: >
      mlflow server 
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      --default-artifact-root s3://mlflow-artifacts/
      --host 0.0.0.0
      --port 5000
    networks:
      - mlops_net

  # -------------------------------------
  # 3. BACKEND (FASTAPI) & FRONTEND
  # -------------------------------------
  model-api:
    build:
      context: ./src
      dockerfile: Dockerfile.api
    container_name: fastapi_backend
    ports:
      - "8001:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
    volumes:
      - ./data:/app/data
    depends_on:
      - mlflow
    networks:
      - mlops_net

  # -------------------------------------
  # 3.5. MONITORAMENTO DESACOPLADO (EVIDENTLY)
  # -------------------------------------
  monitoring:
    build:
      context: ./src
      dockerfile: Dockerfile.monitoring
    container_name: evidently_monitor
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data  # <-- O MONITOR LÊ A MESMA PASTA AQUI
    depends_on:
      - model-api
    networks:
      - mlops_net
  # -------------------------------------
  # 4. MONITORAMENTO (PROMETHEUS & GRAFANA)
  # -------------------------------------
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - mlops_net

  grafana:
    image: grafana/grafana:10.0.3
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./config/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - mlops_net

  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile.frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    depends_on:
      - model-api
    networks:
      - mlops_net

volumes:
  pg_data:
  minio_data:

networks:
  mlops_net:
    driver: bridge