global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'evidently_monitor'
    static_configs:
      - targets: ['monitoring:8002']