FROM python:3.9-slim

WORKDIR /app

RUN pip install --no-cache-dir fastapi uvicorn pydantic "scikit-learn>=1.3.0,<1.6.0" "pandas>=2.0.0,<2.3.0" mlflow boto3

COPY . /app/

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]