FROM python:3.9-slim

WORKDIR /app

# A MÁGICA ESTÁ AQUI TAMBÉM: Blindando a interface do usuário
RUN pip install --no-cache-dir "numpy<2.0.0" streamlit==1.32.0 requests==2.31.0 pandas==2.1.0

COPY . /app/

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]