FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential gcc && rm -rf /var/lib/apt/lists/*

# A MÁGICA ESTÁ AQUI: Bloqueando o Numpy 2.0 para salvar o Pandas 2.1.0 e o Evidently
RUN pip install --no-cache-dir "numpy<2.0.0" pandas==2.1.0 evidently==0.4.17 prometheus-client==0.20.0

COPY . /app/

EXPOSE 8002

CMD ["python", "monitor.py"]