FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential gcc && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir pandas==2.1.0 evidently==0.4.17 prometheus-client==0.20.0

COPY . /app/

EXPOSE 8002

CMD ["python", "monitor.py"]